FROM python:3.11-slim

WORKDIR /app

# Instalar Poetry
RUN pip install --no-cache-dir poetry \
    && poetry config virtualenvs.create false

# Copiar configuraci?n de proyecto y README requerido por poetry
COPY pyproject.toml README.md ./

# Instalar dependencias
RUN poetry install --no-root --no-interaction --no-ansi --without dev

# Copiar c?digo fuente
COPY src/ ./src/

ENV PYTHONPATH=/app
ENV KAFKA_BOOTSTRAP_SERVERS=kafka:29092

CMD ["python", "-m", "src.generator.generator"]
